"""Flashcard MCQ Game data for the AI Teaching Assistant."""

FLASHCARD_DECKS = {
    "Linear Regression": [
        {"question": "What is Linear Regression?",
         "options": ["An unsupervised clustering algorithm", "A supervised learning algorithm modeling linear relationships between features and output", "A reinforcement learning technique", "A dimensionality reduction method"],
         "correct": 1, "explanation": "Linear Regression is a supervised learning algorithm that models a linear relationship: y = wx + b, where w = weight, b = bias."},
        {"question": "What is the cost function used in Linear Regression?",
         "options": ["Cross-Entropy Loss", "Hinge Loss", "Mean Squared Error (MSE)", "Mean Absolute Percentage Error"],
         "correct": 2, "explanation": "MSE = (1/n) Σ(yᵢ - ŷᵢ)² — it measures the average squared difference between predicted and actual values."},
        {"question": "What does an R² score of 1 indicate?",
         "options": ["The model is overfitting", "The model explains 0% variance", "A perfect fit to the data", "The model needs more features"],
         "correct": 2, "explanation": "R² = 1 means the model perfectly explains all variance. R² = 0 means no better than predicting the mean."},
        {"question": "In Multiple Linear Regression, the equation is y = w₁x₁ + w₂x₂ + ... + b. What does 'b' represent?",
         "options": ["The learning rate", "The bias (intercept) term", "The regularization parameter", "The batch size"],
         "correct": 1, "explanation": "The bias 'b' is the intercept — the predicted value when all input features are zero."},
        {"question": "Which is NOT an assumption of Linear Regression?",
         "options": ["Linearity between X and y", "Independence of observations", "Features must be categorical", "Homoscedasticity (constant error variance)"],
         "correct": 2, "explanation": "Features don't need to be categorical. The 4 assumptions are: Linearity, Independence, Homoscedasticity, and Normality of residuals."},
    ],
    "Gradient Descent": [
        {"question": "What does Gradient Descent do?",
         "options": ["Increases the cost function", "Randomly searches parameter space", "Iteratively updates parameters to minimize the cost function", "Generates synthetic data"],
         "correct": 2, "explanation": "Update rule: w = w - α · ∂J/∂w, where α = learning rate. It moves parameters in the direction of steepest descent."},
        {"question": "What happens if the learning rate is too HIGH?",
         "options": ["Model converges very slowly", "Model overshoots the minimum and may diverge", "Training takes less time with better results", "The gradients vanish"],
         "correct": 1, "explanation": "A too-high learning rate causes oscillation or divergence. Too low = painfully slow convergence."},
        {"question": "Which type of Gradient Descent uses a small batch of samples per update?",
         "options": ["Batch GD", "Stochastic GD", "Mini-Batch GD", "Adaptive GD"],
         "correct": 2, "explanation": "Batch GD uses all data, SGD uses 1 sample, Mini-Batch GD uses a small batch — best of both worlds."},
        {"question": "A local minimum is...",
         "options": ["The absolute lowest point of a function", "A point lower than neighbors but not the global lowest", "Always the same as global minimum", "Only found in convex functions"],
         "correct": 1, "explanation": "Local minima are lower than neighbors but NOT the global lowest. Use momentum or Adam to escape them."},
        {"question": "The gradient vector points in the direction of...",
         "options": ["Steepest descent", "Steepest ascent", "Random direction", "Zero change"],
         "correct": 1, "explanation": "The gradient ∇J points toward steepest ASCENT. Gradient Descent moves in the OPPOSITE direction to minimize loss."},
    ],
    "Neural Networks": [
        {"question": "What is the correct layer order in a Neural Network?",
         "options": ["Output → Hidden → Input", "Hidden → Input → Output", "Input → Hidden → Output", "Input → Output → Hidden"],
         "correct": 2, "explanation": "Data flows: Input Layer → Hidden Layer(s) → Output Layer. This is called the forward pass."},
        {"question": "Which activation function outputs max(0, x)?",
         "options": ["Sigmoid", "Tanh", "ReLU", "Softmax"],
         "correct": 2, "explanation": "ReLU (Rectified Linear Unit) = max(0, x). It's the most popular activation for hidden layers."},
        {"question": "What can a Perceptron NOT solve?",
         "options": ["AND gate", "OR gate", "XOR gate", "NOT gate"],
         "correct": 2, "explanation": "A single Perceptron can only solve linearly separable problems. XOR requires at least 2 layers."},
        {"question": "The Universal Approximation Theorem states that a neural network with at least ____ hidden layer(s) can approximate any continuous function.",
         "options": ["Zero", "One", "Three", "Ten"],
         "correct": 1, "explanation": "Just one hidden layer with a non-linear activation is theoretically sufficient, though deeper networks are more practical."},
        {"question": "In the backward pass, what flows back through the network?",
         "options": ["Raw input data", "Predictions", "Error gradients", "New training data"],
         "correct": 2, "explanation": "Forward pass computes predictions; Backward pass sends error gradients back to update weights."},
    ],
    "Backpropagation": [
        {"question": "Backpropagation uses which mathematical rule to compute gradients?",
         "options": ["Product rule", "Quotient rule", "Chain rule", "Power rule"],
         "correct": 2, "explanation": "Chain rule: ∂L/∂w = ∂L/∂ŷ · ∂ŷ/∂z · ∂z/∂w — computes gradients layer by layer."},
        {"question": "What causes the Vanishing Gradient Problem?",
         "options": ["Using ReLU activation", "Sigmoid/Tanh squashing gradients to very small values", "Too few layers", "Large batch sizes"],
         "correct": 1, "explanation": "Sigmoid/Tanh compress outputs to small ranges. Multiplied across many layers, gradients shrink to near zero."},
        {"question": "How do you fix Exploding Gradients?",
         "options": ["Remove all hidden layers", "Gradient clipping", "Increase learning rate", "Use deeper networks"],
         "correct": 1, "explanation": "Gradient clipping caps gradient values. Other fixes: proper initialization, batch normalization."},
        {"question": "In a Computational Graph, nodes represent...",
         "options": ["Training data samples", "Mathematical operations", "Hyperparameters", "Output classes"],
         "correct": 1, "explanation": "Each node = operation, edges = data flow. This structure enables automatic differentiation (autograd)."},
        {"question": "Which technique helps solve the Vanishing Gradient Problem?",
         "options": ["Using more Sigmoid layers", "Using ReLU activation and skip connections", "Reducing network depth to 1 layer", "Using a lower learning rate"],
         "correct": 1, "explanation": "ReLU doesn't squash gradients. Skip connections (ResNets) allow gradients to flow directly to earlier layers."},
    ],
    "Optimization Algorithms": [
        {"question": "SGD with Momentum adds what to standard SGD?",
         "options": ["More training data", "A velocity term to accelerate convergence", "Extra hidden layers", "Dropout regularization"],
         "correct": 1, "explanation": "Momentum: v = β·v + α·∇J, then w = w - v. The velocity β (typically 0.9) helps escape local minima."},
        {"question": "What does 'Adam' stand for?",
         "options": ["Advanced Adaptive Method", "Adaptive Moment Estimation", "Automatic Data Analysis Model", "Accelerated Deep Architecture Method"],
         "correct": 1, "explanation": "Adam combines momentum (1st moment) AND adaptive learning rates (2nd moment). Most popular optimizer!"},
        {"question": "Cosine Annealing is a type of...",
         "options": ["Weight initialization", "Learning rate scheduling", "Data augmentation", "Loss function"],
         "correct": 1, "explanation": "Cosine Annealing smoothly decreases the learning rate following a cosine curve. Other types: step decay, warm-up."},
        {"question": "Batch Normalization normalizes inputs to have...",
         "options": ["Maximum variance", "Zero mean and unit variance", "Uniform distribution", "Negative values only"],
         "correct": 1, "explanation": "BatchNorm → zero mean, unit variance. Benefits: faster training, higher learning rates, reduced vanishing gradients."},
        {"question": "What does Dropout do during training?",
         "options": ["Adds more neurons", "Randomly sets neurons to zero", "Increases all weights by a factor", "Removes entire layers"],
         "correct": 1, "explanation": "Dropout randomly deactivates neurons (rate: 0.2-0.5) to prevent co-adaptation and reduce overfitting."},
    ],
    "CNNs": [
        {"question": "CNN stands for...",
         "options": ["Connected Neural Network", "Convolutional Neural Network", "Conditional Normalization Network", "Cascaded Node Network"],
         "correct": 1, "explanation": "Convolutional Neural Networks are specialized for grid-like data (images). Key layers: Convolution → Pooling → FC."},
        {"question": "In a convolution operation, what slides across the input?",
         "options": ["The bias vector", "A filter (kernel)", "The loss function", "The output layer"],
         "correct": 1, "explanation": "A small filter/kernel slides across input to produce a feature map. Output size = (n - f + 2p)/s + 1."},
        {"question": "Max Pooling takes the _____ value in each window.",
         "options": ["Average", "Minimum", "Maximum", "Median"],
         "correct": 2, "explanation": "Max Pooling = maximum value, Average Pooling = mean value. Pooling reduces spatial dimensions."},
        {"question": "Early CNN layers typically detect...",
         "options": ["Full objects", "Edges and textures", "Semantic meaning", "Entire scenes"],
         "correct": 1, "explanation": "Early layers → edges, textures. Deeper layers → complex patterns (faces, objects). This hierarchy is CNNs' power."},
        {"question": "Which CNN architecture introduced skip connections?",
         "options": ["AlexNet (2012)", "VGG (2014)", "ResNet (2015)", "LeNet (1998)"],
         "correct": 2, "explanation": "ResNet introduced skip/residual connections enabling 152+ layer networks without vanishing gradients."},
    ],
    "RNNs": [
        {"question": "RNNs are designed to process what type of data?",
         "options": ["Only image data", "Sequential/temporal data", "Only tabular data", "Static datasets only"],
         "correct": 1, "explanation": "RNNs maintain a hidden state hₜ = f(W·hₜ₋₁ + U·xₜ + b), creating 'memory' of previous inputs."},
        {"question": "Why can't standard RNNs learn long-range dependencies?",
         "options": ["They have too many parameters", "Vanishing gradients over long sequences", "They process data in parallel", "They lack hidden states"],
         "correct": 1, "explanation": "Gradients shrink exponentially during Backpropagation Through Time (BPTT). Solution: LSTM or GRU."},
        {"question": "How many gates does an LSTM cell have?",
         "options": ["1", "2", "3", "4"],
         "correct": 2, "explanation": "LSTM has 3 gates: Forget (what to discard), Input (what to store), Output (what to output)."},
        {"question": "How is GRU different from LSTM?",
         "options": ["GRU has more gates", "GRU has fewer parameters with 2 gates instead of 3", "GRU can't handle sequences", "GRU requires more memory"],
         "correct": 1, "explanation": "GRU uses 2 gates (Reset + Update) vs LSTM's 3 gates. Fewer parameters, often similar performance."},
        {"question": "Transformers largely replaced RNNs because they...",
         "options": ["Use less data", "Process sequences in parallel via self-attention", "Are simpler architectures", "Don't need training"],
         "correct": 1, "explanation": "Transformers process all positions simultaneously via self-attention. GPT and BERT are Transformer-based."},
    ],
}

def get_deck(topic):
    """Get flashcard MCQ deck for a topic."""
    return FLASHCARD_DECKS.get(topic, [])

def get_all_topics():
    """Get all available topics."""
    return list(FLASHCARD_DECKS.keys())

# ── Memory Game Pairs (concept ↔ definition) ──
MEMORY_PAIRS = {
    "Linear Regression": [
        ("Linear Regression", "y = wx + b"),
        ("MSE", "Mean Squared Error"),
        ("R² Score", "Coefficient of Determination"),
        ("Bias (b)", "Intercept term"),
        ("Homoscedasticity", "Constant error variance"),
        ("Overfitting", "Model memorizes noise"),
    ],
    "Gradient Descent": [
        ("Learning Rate (α)", "Step size for updates"),
        ("SGD", "Stochastic Gradient Descent"),
        ("Mini-Batch", "Small subset per update"),
        ("Local Minimum", "Not the global lowest"),
        ("Gradient (∇J)", "Direction of steepest ascent"),
        ("Convergence", "Reaching the minimum"),
    ],
    "Neural Networks": [
        ("ReLU", "max(0, x)"),
        ("Sigmoid", "1/(1+e⁻ˣ)"),
        ("Perceptron", "Single neuron model"),
        ("Forward Pass", "Input → Prediction"),
        ("Hidden Layer", "Between input & output"),
        ("Activation Fn", "Adds non-linearity"),
    ],
    "Backpropagation": [
        ("Chain Rule", "∂L/∂w = ∂L/∂ŷ · ∂ŷ/∂z · ∂z/∂w"),
        ("Vanishing Gradient", "Gradients shrink to ~0"),
        ("Exploding Gradient", "Gradients grow too large"),
        ("Gradient Clipping", "Caps gradient values"),
        ("Autograd", "Automatic differentiation"),
        ("Backward Pass", "Error flows back"),
    ],
    "Optimization Algorithms": [
        ("Adam", "Adaptive Moment Estimation"),
        ("Momentum (β)", "Velocity term, typically 0.9"),
        ("Batch Norm", "Zero mean, unit variance"),
        ("Dropout", "Randomly deactivate neurons"),
        ("Cosine Annealing", "Smooth LR decay"),
        ("Weight Decay", "L2 regularization"),
    ],
    "CNNs": [
        ("Convolution", "Filter slides across input"),
        ("Pooling", "Downsampling operation"),
        ("Feature Map", "Output of conv filter"),
        ("Stride", "Step size of filter"),
        ("Padding", "Border pixels added"),
        ("ResNet", "Skip connections"),
    ],
    "RNNs": [
        ("LSTM", "3 gates: Forget, Input, Output"),
        ("GRU", "2 gates: Reset, Update"),
        ("Hidden State", "Memory of past inputs"),
        ("BPTT", "Backprop Through Time"),
        ("Attention", "Focus on relevant parts"),
        ("Transformer", "Parallel self-attention"),
    ],
}

def get_memory_pairs(topic):
    """Get memory game pairs for a topic."""
    return MEMORY_PAIRS.get(topic, [])
